name: Keep node version in sync with the one the Playwright version is using

on:
  push:
    branches:
      - "depfu/update/npm/playwright-core-**"

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update .node-version
        run: .github/bin/sync-node-version-from-playwright

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update .node-version after playwright update"
