name: Keep node version and playwright version in sync

on:
  workflow_dispatch:
  push:
    branches:
      - "depfu/update/npm/playwright-core-**"

jobs:
  sync-node-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Sync .node-version with the one that Playwright is using
        run: .github/bin/sync-node-version-from-playwright

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update .node-version after playwright update"

      - name: Sync Playwright version in dockerfile with the one from package.json
        run: .github/bin/sync-playwright-version-to-dockerfile

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update playwright-core in Dockerfile after depfu update"
