name: CI

on:
  push:
    branches:
      - "depfu/update/npm/prettier-**"

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run prettier format
        run: npm run format

      - name: Commit changes
        run: |
          ./.github/bin/commit-format-changes
