name: Prettier

on:
  push:
    branches:
      - "depfu/update/npm/prettier-**"

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run prettier format
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Ran prettier after prettier update"
